### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by thejacer87** [sebastiaanluca/laravel-auto-morph-map#5]
## Description
Installing via composer give me an error.

### Your environment

If you're reporting a bug or asking a specific question, include as many relevant details about your environment so we can reproduce it. The more, the better.

- Operating system and version: Lando laravel recipe - 
```
$ uname -a
Linux c342664ed245 5.0.0-15-generic #16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 GNU/Linux
```
- PHP version: PHP 7.3.4

### Context
here's the output after running 

`composer require sebastiaanluca/laravel-auto-morph-map`

```
Package operations: 1 install, 0 updates, 0 removals
  - Installing sebastiaanluca/laravel-auto-morph-map (3.0.2): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
[2019-06-07 16:57:47] local.ERROR: Unresolvable dependency resolving [Parameter #0 [ <required> $contract ]] in class App\Models\Contract\DashboardDetails {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> $contract ]] in class App\\Models\\Contract\\DashboardDetails at /app/vendor/laravel/framework/src/Illuminate/Container/Container.php:973)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(911): Illuminate\\Container\\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(852): Illuminate\\Container\\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(818): Illuminate\\Container\\Container->resolveDependencies(Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build('App\\\\Models\\\\Cont...')
#4 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('App\\\\Models\\\\Cont...', Array)
#5 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('App\\\\Models\\\\Cont...', Array)
#6 /app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(121): Illuminate\\Foundation\\Application->make('App\\\\Models\\\\Cont...', Array)
#7 /app/vendor/sebastiaanluca/laravel-auto-morph-map/src/Mapper.php(224): app('App\\\\Models\\\\Cont...')
#8 /app/vendor/sebastiaanluca/laravel-auto-morph-map/src/Mapper.php(186): SebastiaanLuca\\AutoMorphMap\\Mapper->getModelName('App\\\\Models\\\\Cont...')
#9 /app/vendor/sebastiaanluca/laravel-auto-morph-map/src/Mapper.php(70): SebastiaanLuca\\AutoMorphMap\\Mapper->getModelAlias('App\\\\Models\\\\Cont...')
#10 /app/vendor/sebastiaanluca/laravel-auto-morph-map/src/Mapper.php(31): SebastiaanLuca\\AutoMorphMap\\Mapper->getModelMap(Array)
#11 /app/vendor/sebastiaanluca/laravel-auto-morph-map/src/AutoMorphMapServiceProvider.php(40): SebastiaanLuca\\AutoMorphMap\\Mapper->map()
#12 [internal function]: SebastiaanLuca\\AutoMorphMap\\AutoMorphMapServiceProvider->boot()
#13 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(827): Illuminate\\Container\\Container->call(Array)
#18 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(810): Illuminate\\Foundation\\Application->bootProvider(Object(SebastiaanLuca\\AutoMorphMap\\AutoMorphMapServiceProvider))
#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(SebastiaanLuca\\AutoMorphMap\\AutoMorphMapServiceProvider), 18)
#20 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): array_walk(Array, Object(Closure))
#21 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#22 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#23 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(322): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#24 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#25 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 {main}
"} 


In Container.php line 973:
                                                                                                                           
  Unresolvable dependency resolving [Parameter #0 [ <required> $contract ]] in class App\Models\Contract\DashboardDetails  
                                                                                                                           

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

```

**Comment by thejacer87** [comment]
my bad, it was an issue with one of our models... i didnt recognize it at first (big team project)
carry on
